apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-cert
  namespace: pihole
spec:
  secretName: pihole-tls
  issuerRef:
    name: cloudflare-letsencrypt-issuer
    kind: ClusterIssuer
  commonName: "technolev.work"
  dnsNames:
    - "pihole.techolev.work"
