---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: { { CLOUDFLARE_API_TOKEN } }
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt-issuer
spec:
  acme:
    email: { { CLOUDFLARE_EMAIL } }
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: { { CLOUDFLARE_EMAIL } }
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
